### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by cnu-Dawn** [yurimjeon1892/EFGH#9]
=> using 'cuda' for computation.
=> checking ckpt dir...
=> creating model and optimizer... 
Traceback (most recent call last):
  File "main.py", line 238, in <module>
    main()
  File "main.py", line 126, in main
    model = nets.__dict__[args['arch'] + 'Backbone'](args).to(device)
  File "/home/hdp/EFGH/nets/efghbackbone.py", line 16, in __init__
    self.E = Enet(args)     
  File "/home/hdp/EFGH/nets/enet.py", line 22, in __init__
    self.generate_data = GenerateData(dim, scales_filter_map, self.device)        
  File "/home/hdp/EFGH/nets/generate_data.py", line 51, in __init__
    traversal.go(center, hash_table)
  File "/home/hdp/EFGH/nets/transforms.py", line 111, in go
    self.walk_cuboid(start_key, 0, False, walking_keys, hash_table_list)
  File "/home/hdp/EFGH/nets/transforms.py", line 119, in walk_cuboid
    self.walk_cuboid(walking_keys[d], d + 1, has_zero or (i == 0), walking_keys, hash_table_list)
  File "/home/hdp/EFGH/nets/transforms.py", line 119, in walk_cuboid
    self.walk_cuboid(walking_keys[d], d + 1, has_zero or (i == 0), walking_keys, hash_table_list)
  File "/home/hdp/EFGH/nets/transforms.py", line 119, in walk_cuboid
    self.walk_cuboid(walking_keys[d], d + 1, has_zero or (i == 0), walking_keys, hash_table_list)
  File "/home/hdp/EFGH/nets/transforms.py", line 120, in walk_cuboid
    walking_keys[d] = advance_in_dimension(self.d + 1, 1, d, walking_keys[d])
TypeError: expected dtype object, got 'numpy.dtype[int64]'

**Comment by cnu-Dawn** [comment]
I installed numba and encountered the following error
ImportError: cannot import name 'cffi_support' from 'numba' (/home/hdp/anaconda3/envs/efgh/lib/python3.8/site-packages/numba/__init__.py)
May I ask which version is correct？

**Comment by cnu-Dawn** [comment]
Have solved. Thanks!
